spring:
  datasource:
    url: jdbc:postgresql://postgres.etiya.com:5432/productdb
    driver-class-name: org.postgresql.Driver
    username: postgres
    password: postgres
  data:
    redis:
      host: redis.etiya.com
      port: 6379
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: https://keycloak.etiya.com/realms/etiya-crm-project
  cloud:
    stream:
      kafka:
        binder:
          brokers: kafka.etiya.com:9092

eureka:
  client:
    service-url:
      defaultZone: http://eureka.etiya.com/eureka/
