spring:
  datasource:
    url: jdbc:postgresql://postgres.etiya.com:5432/orderdb
    driver-class-name: org.postgresql.Driver
    username: postgres
    password: postgres
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: https://keycloak.etiya.com/realms/etiya-crm-project

eureka:
  client:
    service-url:
      defaultZone: http://eureka.etiya.com/eureka/
